name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name : Install Lib
      run: sudo apt-get install libsdl2-dev libsdl2-ttf-dev
    - name : Build Cmake
      run : ./CMakeGCC.sh
            cd bin/make
            make
    - name: execute
      run: cd bin/make/Release
           ./sobel
